### ISSUE TITLE
🔗 日报提交 | justjavac

### ISSUE THREAD

**Issue by sunhaoxiang** [d2-projects/d2-awesome#217]
**:hash: 标题** : 月下载量千万的 npm 包被黑客篡改，Vue 开发者可能正在遭受攻击

**:page_with_curl: 介绍** : justjavac

**:link: 链接** : [https://mp.weixin.qq.com/s/IaOWxG0XLvn2znvvP1dmwA](https://mp.weixin.qq.com/s/IaOWxG0XLvn2znvvP1dmwA)

**:pencil2: Markdown**

```
- name: 新闻
  list:
  - name: justjavac
    note: justjavac
    url: https://mp.weixin.qq.com/s/IaOWxG0XLvn2znvvP1dmwA
```

由 iOS12 捷径 APP 自动提交

**Comment by ishenyi** [comment]
这个我抢先一步分享了，重复啦，不好意思😆
